export const blurImages = {
  welcome: 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4WAoAAAAgAAAACQAABQAAVlA4IBwAAAAwAQCdASoKAAYAAkA4JaQAA3AA/vh9gxe4AAAA',
  sponsor: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4WAoAAAAgAAAACQAABQAAVlA4IDIAAADwAQCdASoKAAYAAkA4JZwCdAD0YaT3EgAA/vqadESaxrbmsMxz9SOU59+OiaWtUPjgAA==',
  ['new-feature']: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4WAoAAAAgAAAACQAABQAAVlA4IDIAAACwAQCdASoKAAYAAkA4JZwCdAEOI+oAAP79dh2g8mYlUeufP+HaQfTKoYyXoSZxT2AAAA==',
}